import { ReactNode } from "react";
import { Inter } from "next/font/google";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";

import { Toaster } from "@/shared/ui/sonner";
import { ConvexClientProvider } from "./providers/convex-client-provider";
import { ModalsProvider } from "./providers/modals-provider";
// import { ThemeProvider } from "./providers/theme-provider";

import type { Metadata } from "next";

import "./styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Slack Clone",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body className={inter.className}>
          <ConvexClientProvider>
            {/* <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            > */}
            <ModalsProvider />
            <Toaster />
            {children}
            {/* </ThemeProvider> */}
          </ConvexClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
